project:
  type: book
  output-dir: docs

book:
  title: "Learning to Fly"
  author: "Tero Jalkanen"
  date: "1/14/2023"
  chapters:
    - index.qmd
    - intro.qmd
#    - words.qmd
#    - bigrams.qmd
    - summary.qmd
    - references.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
    
execute:
  freeze: auto